// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package schemas

type LoginUser struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterUser struct {
	Credentials *LoginUser `json:"credentials"`
}
