###

POST http://localhost:8080/query
Content-Type: application/json

{
  "query": "mutation RegisterUser($input: RegisterUserInput!) {registerUser(input: $input)}",
  "variables": {
    "input": {
      "email": "alexqwerty98@yandex.ru",
      "password": "Qwer1234@",
      "displayName": "DKhorkov"
    }
  }
}

###

POST http://localhost:8080/query
Content-Type: application/json

{
  "query": "mutation VerifyUserEmail($input: VerifyUserEmailInput!) { verifyUserEmail(input: $input) }",
  "variables": {
    "input": {
      "verifyEmailToken": "MzE"
    }
  }
}

###

POST http://localhost:8080/query
Content-Type: application/json

{
  "query": "mutation LoginUser($input: LoginUserInput!) {loginUser(input: $input)}",
  "variables": {
    "input": {
      "email": "alexqwerty35@yandex.ru",
      "password": "Qwer1234@"
    }
  }
}

###

POST http://localhost:8080/query
Content-Type: application/json
Cookie: refreshToken=ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SmxlSEFpT2pFM05EUXdORFV5TkRFc0luWmhiSFZsSWpvaVpYbEthR0pIWTJsUGFVcEpWWHBKTVU1cFNYTkpibEkxWTBOSk5rbHJjRmhXUTBvNUxtVjVTbXhsU0VGcFQycEZNMDVFVFRCT1JFVjZUa1JGYzBsdVdtaGlTRlpzU1dwdmVrMVlNQzQ0WlZWelkwRmlTVXRLUmtKbWFtdE9SVmRDVmpka2VYUmZOR3c1TFVveVFXaFZZVWczVXpKeFNUVnpJbjAueHFubXRERHJvNktCeFhFeW5fRU5iS01wbDlOYUZDd1dRaWxBNkFZcGstUQ

{
  "query": "mutation { refreshTokens }"
}

###

POST http://localhost:8080/query
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDEyOTMxMTUsInZhbHVlIjozMX0.7YTO84thnGVDalv-w_24hksTneL0NnVBGiG5oUMOMWQ

{
  "query": "query { me { id displayName email emailConfirmed phone phoneConfirmed telegram telegramConfirmed avatar createdAt updatedAt } }"
}

###

POST http://localhost:8080/query
Content-Type: multipart/form-data; boundary=boundary
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDE1NDI2NTQsInZhbHVlIjozMX0.Lj88PjFR3SQUVIMkJVnrH_tZWLgUVzr_rGlFHL2NY5k

--boundary
Content-Disposition: form-data; name="operations"

{
  "query": "mutation UpdateToy($input: UpdateToyInput!) { updateToy(input: $input) }",
  "variables": {
    "input": {
      "id": "2",
      "categoryId": "1",
      "name": "Super Toy",
      "description": "A fantastic toy for kids",
      "price": 29.99,
      "quantity": 100,
      "tags": ["educational", "fun"],
      "attachments": [null, null]
    }
  }
}
--boundary
Content-Disposition: form-data; name="map"

{
  "0": ["variables.input.attachments.0"],
  "1": ["variables.input.attachments.1"]
}
--boundary
Content-Disposition: form-data; name="0"; filename="image1.jpg"
Content-Type: image/jpeg

< /home/dkhorkov/Downloads/t1.png
--boundary
Content-Disposition: form-data; name="1"; filename="image2.jpg"
Content-Type: image/jpeg

< /home/dkhorkov/Downloads/m3.png
--boundary--

###

POST http://localhost:8080/query
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDE1NDM1NjYsInZhbHVlIjozMX0.GZIubVZ50wVNEeN-CGIwEm25E14IzNtaTIAJsmPYifI

{
  "query": "mutation DeleteToy($input: DeleteToyInput!) { deleteToy(input: $input) }",
  "variables": {
    "input": {
      "id": "2"
    }
  }
}

###

POST http://localhost:8080/query
Content-Type: application/json

{
  "query": "query { tickets { id user { id displayName email } category { id name } name description price quantity createdAt updatedAt tags { id name } attachments { id ticketID link createdAt updatedAt } } }"
}

###

POST http://localhost:8080/query
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDIwNTQ3NjYsInZhbHVlIjozMX0.Lh0bAZu6M8iHpRhdh9QFE17f_DHauHnBYFV7OJaYSko

{
  "query": "query { myResponds { id ticket { id user { id displayName email } category { id name } name description price quantity createdAt updatedAt tags { id name } attachments { id ticketID link createdAt updatedAt } } master { id user { id displayName email } info createdAt updatedAt } price comment createdAt updatedAt } }"
}

###

POST http://localhost:8080/query
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDIwNTQ3NjYsInZhbHVlIjozMX0.Lh0bAZu6M8iHpRhdh9QFE17f_DHauHnBYFV7OJaYSko

{
  "query": "mutation RespondToTicket($input: RespondToTicketInput!) { respondToTicket(input: $input) }",
  "variables": {
    "input": {
      "ticketId": "1",
      "price": 50.99,
      "comment": "I can help with this task!"
    }
  }
}

###

POST http://localhost:8080/query
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDIxMTUzNjUsInZhbHVlIjozMX0.J1sCJmskFP7K6iMRXA6MORHrNRqTgmfHRr6rfliHOqo

{
  "query": "query { myResponds { id ticket { id user { id displayName email } category { id name } name description price quantity createdAt updatedAt tags { id name } attachments { id ticketID link createdAt updatedAt } } master { id user { id displayName email } info createdAt updatedAt } price comment createdAt updatedAt } }"
}

###

POST http://localhost:8080/query
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDIxMTUzNjUsInZhbHVlIjozMX0.J1sCJmskFP7K6iMRXA6MORHrNRqTgmfHRr6rfliHOqo

{
  "query": "mutation UpdateRespond($input: UpdateRespondInput!) { updateRespond(input: $input) }",
  "variables": {
    "input": {
      "id": "4",
      "price": 30.99,
      "comment": "Updated price and comment"
    }
  }
}

###

POST http://localhost:8080/query
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDIxMTUzNjUsInZhbHVlIjozMX0.J1sCJmskFP7K6iMRXA6MORHrNRqTgmfHRr6rfliHOqo

{
  "query": "mutation DeleteRespond($input: DeleteRespondInput!) { deleteRespond(input: $input) }",
  "variables": {
    "input": {
      "id": "1"
    }
  }
}

###

POST http://localhost:8080/query
Content-Type: application/json

{
  "query": "query { masters { id user { id displayName email emailConfirmed phone phoneConfirmed telegram telegramConfirmed avatar createdAt updatedAt } info createdAt updatedAt } }"
}

###

POST http://localhost:8080/query
Content-Type: application/json


{
  "query": "query Master($id: ID!) { master(id: $id) { id user { id displayName email emailConfirmed phone phoneConfirmed telegram telegramConfirmed avatar createdAt updatedAt } info createdAt updatedAt } }",
  "variables": {
    "id": "1"
  }
}

###

POST http://localhost:8080/query
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDIxMzkxMjIsInZhbHVlIjozMX0.CQLc6W6rv4yCfVUg3gSqC-jJCta0z0-nZOOB8KWW7yI

{
  "query": "mutation UpdateMaster($input: UpdateMasterInput!) { updateMaster(input: $input) }",
  "variables": {
    "input": {
      "id": "1",
      "info": "Updated master information"
    }
  }
}

###

POST http://localhost:8080/query
Content-Type: multipart/form-data; boundary=boundary
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDI1NzE3NDUsInZhbHVlIjozMX0.oAjV5QQe97Fed5sdajTpu0NED30rSoSeC7gPChQZ1q8

--boundary
Content-Disposition: form-data; name="operations"

{
  "query": "mutation CreateTicket($input: CreateTicketInput!) { createTicket(input: $input) }",
  "variables": {
    "input": {
      "categoryId": "1",
      "name": "Super Toy",
      "description": "A fantastic toy for kids",
      "price": 29.99,
      "quantity": 100,
      "tags": ["educational", "fun"],
      "attachments": [null, null]
    }
  }
}
--boundary
Content-Disposition: form-data; name="map"

{
  "0": ["variables.input.attachments.0"],
  "1": ["variables.input.attachments.1"]
}
--boundary
Content-Disposition: form-data; name="0"; filename="image1.jpg"
Content-Type: image/jpeg

< /home/dkhorkov/Изображения/Снимки экрана/t1.png
--boundary
Content-Disposition: form-data; name="1"; filename="image2.jpg"
Content-Type: image/jpeg

< /home/dkhorkov/Изображения/Снимки экрана/t2.png
--boundary--

###

POST http://localhost:8080/query
Content-Type: multipart/form-data; boundary=boundary
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDI1NzI4OTAsInZhbHVlIjozMX0.fhW-rtppEszFu5M20xP-60pYSm_hJ79umNC_8HNb8bg

--boundary
Content-Disposition: form-data; name="operations"

{
  "query": "mutation UpdateTicket($input: UpdateTicketInput!) { updateTicket(input: $input) }",
  "variables": {
    "input": {
      "id": "1",
      "categoryId": "2",
      "name": "Updated Toy Name",
      "description": "Updated description for the toy",
      "price": 39.99,
      "quantity": 50,
      "tags": ["educational", "fun", "new"],
      "attachments": [null, null]
    }
  }
}
--boundary
Content-Disposition: form-data; name="map"

{
  "0": ["variables.input.attachments.0"],
  "1": ["variables.input.attachments.1"]
}
--boundary
Content-Disposition: form-data; name="0"; filename="image1.jpg"
Content-Type: image/jpeg

< /home/dkhorkov/Изображения/Снимки экрана/t1.png
--boundary
Content-Disposition: form-data; name="1"; filename="t2.png"
Content-Type: image/jpeg

< /home/dkhorkov/Изображения/Снимки экрана/t2.png
--boundary--

###

POST http://localhost:8080/query
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDI1NzI4OTAsInZhbHVlIjozMX0.fhW-rtppEszFu5M20xP-60pYSm_hJ79umNC_8HNb8bg

{
  "query": "mutation DeleteTicket($input: DeleteTicketInput!) { deleteTicket(input: $input) }",
  "variables": {
    "input": {
      "id": "10"
    }
  }
}

###

POST http://localhost:8080/query
Content-Type: application/json

{
  "query": "mutation SendForgetPasswordMessage($input: SendForgetPasswordMessageInput!) { sendForgetPasswordMessage(input: $input) }",
  "variables": {
    "input": {
      "email": "alexqwerty35@yandex.ru"
    }
  }
}

###

POST http://localhost:8080/query
Content-Type: application/json

{
  "query": "mutation ForgetPassword($input: ForgetPasswordInput!) { forgetPassword(input: $input) }",
  "variables": {
    "input": {
      "forgetPasswordToken": "MzE",
      "newPassword": "Qwer1234@"
    }
  }
}

###

POST http://localhost:8080/query
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDU1ODk3NTYsInZhbHVlIjozMX0.jpBGjGAjw9yc83D8bSi8fxu-aT5DBv9kK3H-CONToK8

{
  "query": "query { masterByUser { id user { id displayName email emailConfirmed phone phoneConfirmed telegram telegramConfirmed avatar createdAt updatedAt } info createdAt updatedAt } }"
}
