// Code generated by MockGen. DO NOT EDIT.
// Source: services.go
//
// Generated by this command:
//
//	mockgen -source=services.go -destination=../../mocks/services/tickets_service.go -package=mockservices -exclude_interfaces=ToysService,FileStorageService,SsoService,NotificationsService
//

// Package mockservices is a generated GoMock package.
package mockservices

import (
	context "context"
	reflect "reflect"

	entities "github.com/DKhorkov/hmtm-bff/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockTicketsService is a mock of TicketsService interface.
type MockTicketsService struct {
	ctrl     *gomock.Controller
	recorder *MockTicketsServiceMockRecorder
	isgomock struct{}
}

// MockTicketsServiceMockRecorder is the mock recorder for MockTicketsService.
type MockTicketsServiceMockRecorder struct {
	mock *MockTicketsService
}

// NewMockTicketsService creates a new mock instance.
func NewMockTicketsService(ctrl *gomock.Controller) *MockTicketsService {
	mock := &MockTicketsService{ctrl: ctrl}
	mock.recorder = &MockTicketsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTicketsService) EXPECT() *MockTicketsServiceMockRecorder {
	return m.recorder
}

// CountTickets mocks base method.
func (m *MockTicketsService) CountTickets(ctx context.Context, filters *entities.TicketsFilters) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTickets", ctx, filters)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTickets indicates an expected call of CountTickets.
func (mr *MockTicketsServiceMockRecorder) CountTickets(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTickets", reflect.TypeOf((*MockTicketsService)(nil).CountTickets), ctx, filters)
}

// CountUserTickets mocks base method.
func (m *MockTicketsService) CountUserTickets(ctx context.Context, userID uint64, filters *entities.TicketsFilters) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUserTickets", ctx, userID, filters)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUserTickets indicates an expected call of CountUserTickets.
func (mr *MockTicketsServiceMockRecorder) CountUserTickets(ctx, userID, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUserTickets", reflect.TypeOf((*MockTicketsService)(nil).CountUserTickets), ctx, userID, filters)
}

// CreateTicket mocks base method.
func (m *MockTicketsService) CreateTicket(ctx context.Context, ticketData entities.CreateTicketDTO) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTicket", ctx, ticketData)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTicket indicates an expected call of CreateTicket.
func (mr *MockTicketsServiceMockRecorder) CreateTicket(ctx, ticketData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTicket", reflect.TypeOf((*MockTicketsService)(nil).CreateTicket), ctx, ticketData)
}

// DeleteRespond mocks base method.
func (m *MockTicketsService) DeleteRespond(ctx context.Context, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRespond", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRespond indicates an expected call of DeleteRespond.
func (mr *MockTicketsServiceMockRecorder) DeleteRespond(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRespond", reflect.TypeOf((*MockTicketsService)(nil).DeleteRespond), ctx, id)
}

// DeleteTicket mocks base method.
func (m *MockTicketsService) DeleteTicket(ctx context.Context, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTicket", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTicket indicates an expected call of DeleteTicket.
func (mr *MockTicketsServiceMockRecorder) DeleteTicket(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTicket", reflect.TypeOf((*MockTicketsService)(nil).DeleteTicket), ctx, id)
}

// GetRespondByID mocks base method.
func (m *MockTicketsService) GetRespondByID(ctx context.Context, id uint64) (*entities.Respond, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRespondByID", ctx, id)
	ret0, _ := ret[0].(*entities.Respond)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRespondByID indicates an expected call of GetRespondByID.
func (mr *MockTicketsServiceMockRecorder) GetRespondByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRespondByID", reflect.TypeOf((*MockTicketsService)(nil).GetRespondByID), ctx, id)
}

// GetTicketByID mocks base method.
func (m *MockTicketsService) GetTicketByID(ctx context.Context, id uint64) (*entities.RawTicket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTicketByID", ctx, id)
	ret0, _ := ret[0].(*entities.RawTicket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTicketByID indicates an expected call of GetTicketByID.
func (mr *MockTicketsServiceMockRecorder) GetTicketByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTicketByID", reflect.TypeOf((*MockTicketsService)(nil).GetTicketByID), ctx, id)
}

// GetTicketResponds mocks base method.
func (m *MockTicketsService) GetTicketResponds(ctx context.Context, ticketID uint64) ([]entities.Respond, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTicketResponds", ctx, ticketID)
	ret0, _ := ret[0].([]entities.Respond)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTicketResponds indicates an expected call of GetTicketResponds.
func (mr *MockTicketsServiceMockRecorder) GetTicketResponds(ctx, ticketID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTicketResponds", reflect.TypeOf((*MockTicketsService)(nil).GetTicketResponds), ctx, ticketID)
}

// GetTickets mocks base method.
func (m *MockTicketsService) GetTickets(ctx context.Context, pagination *entities.Pagination, filters *entities.TicketsFilters) ([]entities.RawTicket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTickets", ctx, pagination, filters)
	ret0, _ := ret[0].([]entities.RawTicket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTickets indicates an expected call of GetTickets.
func (mr *MockTicketsServiceMockRecorder) GetTickets(ctx, pagination, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTickets", reflect.TypeOf((*MockTicketsService)(nil).GetTickets), ctx, pagination, filters)
}

// GetUserResponds mocks base method.
func (m *MockTicketsService) GetUserResponds(ctx context.Context, userID uint64) ([]entities.Respond, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserResponds", ctx, userID)
	ret0, _ := ret[0].([]entities.Respond)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserResponds indicates an expected call of GetUserResponds.
func (mr *MockTicketsServiceMockRecorder) GetUserResponds(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserResponds", reflect.TypeOf((*MockTicketsService)(nil).GetUserResponds), ctx, userID)
}

// GetUserTickets mocks base method.
func (m *MockTicketsService) GetUserTickets(ctx context.Context, userID uint64, pagination *entities.Pagination, filters *entities.TicketsFilters) ([]entities.RawTicket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserTickets", ctx, userID, pagination, filters)
	ret0, _ := ret[0].([]entities.RawTicket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserTickets indicates an expected call of GetUserTickets.
func (mr *MockTicketsServiceMockRecorder) GetUserTickets(ctx, userID, pagination, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserTickets", reflect.TypeOf((*MockTicketsService)(nil).GetUserTickets), ctx, userID, pagination, filters)
}

// RespondToTicket mocks base method.
func (m *MockTicketsService) RespondToTicket(ctx context.Context, respondData entities.RespondToTicketDTO) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RespondToTicket", ctx, respondData)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RespondToTicket indicates an expected call of RespondToTicket.
func (mr *MockTicketsServiceMockRecorder) RespondToTicket(ctx, respondData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RespondToTicket", reflect.TypeOf((*MockTicketsService)(nil).RespondToTicket), ctx, respondData)
}

// UpdateRespond mocks base method.
func (m *MockTicketsService) UpdateRespond(ctx context.Context, respondData entities.UpdateRespondDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRespond", ctx, respondData)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRespond indicates an expected call of UpdateRespond.
func (mr *MockTicketsServiceMockRecorder) UpdateRespond(ctx, respondData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRespond", reflect.TypeOf((*MockTicketsService)(nil).UpdateRespond), ctx, respondData)
}

// UpdateTicket mocks base method.
func (m *MockTicketsService) UpdateTicket(ctx context.Context, ticketData entities.UpdateTicketDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTicket", ctx, ticketData)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTicket indicates an expected call of UpdateTicket.
func (mr *MockTicketsServiceMockRecorder) UpdateTicket(ctx, ticketData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTicket", reflect.TypeOf((*MockTicketsService)(nil).UpdateTicket), ctx, ticketData)
}
