// Code generated by MockGen. DO NOT EDIT.
// Source: repositories.go
//
// Generated by this command:
//
//	mockgen -source=repositories.go -destination=../../mocks/repositories/notifications_repository.go -package=mockrepositories -exclude_interfaces=ToysRepository,FileStorageRepository,TicketsRepository,SsoRepository
//

// Package mockrepositories is a generated GoMock package.
package mockrepositories

import (
	context "context"
	reflect "reflect"

	entities "github.com/DKhorkov/hmtm-bff/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificationsRepository is a mock of NotificationsRepository interface.
type MockNotificationsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationsRepositoryMockRecorder
	isgomock struct{}
}

// MockNotificationsRepositoryMockRecorder is the mock recorder for MockNotificationsRepository.
type MockNotificationsRepositoryMockRecorder struct {
	mock *MockNotificationsRepository
}

// NewMockNotificationsRepository creates a new mock instance.
func NewMockNotificationsRepository(ctrl *gomock.Controller) *MockNotificationsRepository {
	mock := &MockNotificationsRepository{ctrl: ctrl}
	mock.recorder = &MockNotificationsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationsRepository) EXPECT() *MockNotificationsRepositoryMockRecorder {
	return m.recorder
}

// GetUserEmailCommunications mocks base method.
func (m *MockNotificationsRepository) GetUserEmailCommunications(ctx context.Context, userID uint64) ([]entities.Email, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserEmailCommunications", ctx, userID)
	ret0, _ := ret[0].([]entities.Email)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserEmailCommunications indicates an expected call of GetUserEmailCommunications.
func (mr *MockNotificationsRepositoryMockRecorder) GetUserEmailCommunications(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserEmailCommunications", reflect.TypeOf((*MockNotificationsRepository)(nil).GetUserEmailCommunications), ctx, userID)
}
