// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphqlapi

type AddToyInput struct {
	CategoryID  int     `json:"CategoryID"`
	Name        string  `json:"Name"`
	Description string  `json:"Description"`
	Price       float64 `json:"Price"`
	Quantity    int     `json:"Quantity"`
	TagsIDs     []int   `json:"TagsIDs"`
}

type LoginUserInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterMasterInput struct {
	Info string `json:"info"`
}

type RegisterUserInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}
